apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      # it is making sure that only backend pods will have access to service account(sa)
      # and service account has required role from irsa.tf(aws_iam_role) and hence now passed to backend pods
      serviceAccountName: backend-sa    
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          livenessProbe:
            httpGet: { path: /api/hello, port: 3000 }
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /api/hello, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: docdb-mongo-uri-k8s
                  key: MONGO_URI
          volumeMounts:
            - name: docdb-ca
              mountPath: /certs
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: docdb-ca
          configMap:
            name: {{ .Values.docdb.configMapName }}
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: docdb-mongo-uri # Points to your SecretProviderClass
