apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travelmemory-ingress
  annotations:
    # Tells AWS to create an Application Load Balancer
    kubernetes.io/ingress.class: alb
    # Makes the Load Balancer accessible from the public internet
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Routes traffic directly to the Pod IPs (highly efficient)
    alb.ingress.kubernetes.io/target-type: ip

    # Backend Health Check
    alb.ingress.kubernetes.io/healthcheck-path-backend: /api/hello
    alb.ingress.kubernetes.io/healthcheck-port-backend: '3000'
    
    # Frontend Health Check (Nginx usually serves index.html at /)
    alb.ingress.kubernetes.io/healthcheck-path-frontend: /
    alb.ingress.kubernetes.io/healthcheck-port-frontend: '80'
    
    alb.ingress.kubernetes.io/success-codes: '200'

spec:
  rules:
    - http:
        paths:
        # Backend API traffic
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.port }}
          # Frontend traffic
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ .Values.frontend.port }}
          