apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travelmemory-ingress
  annotations:
    # Tells AWS to create an Application Load Balancer
    kubernetes.io/ingress.class: alb
    # Makes the Load Balancer accessible from the public internet
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Routes traffic directly to the Pod IPs (highly efficient)
    alb.ingress.kubernetes.io/target-type: ip
    # Add these two lines to strip '/api' before it hits your pod
    alb.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
        # Backend API traffic
          - path: /api/(.*)  # Captures everything after /api/
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.port }}
          # Frontend traffic
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ .Values.frontend.port }}
          