apiVersion: v1
kind: ServiceAccount
metadata:
  name: anomaly-detector-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::446056240219:role/eks-pipeline-anomaly-detector
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: anomaly-detector
  namespace: default
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 3   # Keeps only the last 3 successful jobs
  failedJobsHistoryLimit: 1       # Keeps only the last 1 failed job
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: anomaly-detector-sa
          restartPolicy: OnFailure
          containers:
            - name: anomaly-detector
              image: python:3.12-slim
              command: ["/bin/sh", "-c"]
              args:
                - |
                  pip install boto3 requests --quiet &&
                  python3 /scripts/anomaly-detector.py
              env:
                - name: CLUSTER_NAME
                  value: "eks-pipeline"
                - name: AWS_DEFAULT_REGION
                  value: "ap-south-1"
                - name: Z_SCORE_THRESHOLD
                  value: "3.0"
                - name: LOOKBACK_HOURS
                  value: "168"
              volumeMounts:
                - name: script
                  mountPath: /scripts
          volumes:
            - name: script
              configMap:
                name: anomaly-detector-script
