# Create a SecretProviderClass that points to the AWS Secret.

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: docdb-mongo-uri
spec:
  provider: aws. # Or azure, vault, gcp, akeyless, etc.
  parameters:
    objects: |
      - objectName: "travelmemory/docdb-mongo-uri"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MONGO_URI"
            objectAlias: "MONGO_URI"
  secretObjects:  # Optional: sync to native Kubernetes Secret
    - secretName: docdb-mongo-uri-k8s  # Creates a native Kubernetes Secret named docdb-mongo-uri-k8s.
      type: Opaque
      data:
        - objectName: "MONGO_URI"   # Points to the objectAlias above
          key: MONGO_URI
